
#+SETUPFILE: note.cfg
#+Title: Alternative lithography and algorithmic molecular patterning
+ *좌장 : 전석우(KAIST)*



* 1st talk (윤동기, KAIST)
**  Topological defects of soft matter in confined geometry
*keywords*
| topological defects | LC(Liquid Crystal)                 | Lambda plate            |
| topological soliton | Physical Unclonable functions(PUF) | Cholesteric Fingere(CF) |

topological defect

LC(Liquid Crystal) topological defects as Model systems , lambda plate- nature 2013 493 200-205   [[https://www.nature.com/articles/nature11710][link]]

TD(topological defect) generate and making patterns using it

planar - normal deposition, homeotropic(perpendicular)

fabrication of topological defects array sci adv 2018 4 aau8064   [[https://www.science.org/doi/10.1126/sciadv.aau8064][link]]

topological defects array in the patterned nematic LCs

CLC(cholesteric (= chiral) Liquid Crystal) >> finger print texture

Topological soliton (정보를 가지고 있으며, 외부 간섭에 의해 정보가 변하지 않는 입자)
Toron, Skymion, Heliknotons, Cholesteric finger(CF)
adv mater 2022 34 2201749   [[https://onlinelibrary.wiley.com/doi/abs/10.1002/adma.202201749][link]]

phase transition of the torons

phase transition of CF3

Fabrication of periodic topological solitons array

physical unclonable functions(PUF) with optical signals nat commun 2020 11 328   [[https://www.nature.com/articles/s41467-019-14066-5][link]]
- case study by ML gives us 10^56 case

PUF using topological solitons array

Q1. unit을 더 줄일 수 있는가?
A1. 오히려 scale up을 통해 일반 카메라를 통해서도 PUF를 confirm할 수 있다.

Q2. 그렇다면 이 방식의 이점은 무엇인가?
A2. 제작과 갱신이 용이하다. 진품을 증빙하고자 할 때 사용자가 편리하고 핸드폰 등의 상용장비로도 검증이 가능하다.

* 2nd talk (심우영, 연세대)

**  Parallel nanofabrication and nanoimaging
*keywords*
| conformal contact       | shadow mask                         | 30~40nm resolution |
| far-field to near-field | BPSM(Binary-state probe microscopy) | multi probe system |

programmable nanowire circuit for nanoprocessor

wafer-scale ebeam lithography - CNS Elionix (37nm flusible)

Far vs Near-field photolitho
shadow mask - gap between photomask makes far-field litho
tip guide-line - make pdms beam guide make it sure near-field by conformal contact
projection - making informal contact by making mask with the material like PDMS substrate patterned by metal contact

rough surface high-res photolith nat com 11 805 2020 park s kim G and shim W   [[https://www.nature.com/articles/s41467-020-14439-1][link]]

cantilever-based single tip imaging >> cantilever-based single tip patterning >> catilever-based multiple tip patterning >> cantilever-free multiple tip patterning >> cantilever-free multiple tip imaging

cantilever-free : cheap cost for making tips

BSPM(Binary-state probe microscopy, 10X10 probe) - lateral res ~780nm, height res ~13nm

Q1. 100개의 팁이 전부 따로 측정을 하는가?
A1. 맞다. 그래서 스케일 업이 어렵다.

Q2. quantum conductance가 보이는가?
A2. quantum conductance 개념은 잘 모르겠으나, 저항이 step 모양으로 측정되는 것은 확인했다.

Q3.
A3. BSPM을 보면 ebeam(CNS)에 비해 선폭이 blur된 것 같은데 100% conformal contact을 보장할 순 없고, 향상되었다고만 말할 수 있다.

* 3rd talk (김현우, 고려대)
**  Microfluidic multi-junction desing for high-viscosity fluids
*keywords*
| particle embeding  | functionalized particle | BCP matrix  | position registry |
| large area uniform | orientation control     | stretchable |                   |

fabricate micro lens array using the droplet genrated by controlled flow rate of high viscosity liquid

detailed control of the viscosity liquid

secure uniformity of flow speed considering the resistance of the flow difference at each position

several micro meters diameter but quite uniform and cheap method for large area fabrication
